apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-up-day
  namespace: web-app
spec:
  schedule: "0 7 * * *"  # Каждый день в 7:00
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: scaler
          containers:
            - name: scaler
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  kubectl patch hpa web-app-hpa -n web-app -p '{"spec":{"minReplicas":4}}'
          restartPolicy: OnFailure